### ISSUE TITLE
libocrivist won't compile with tesseract 3.02

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sonwendi/ocrivist#1]
```
Debian x64 unstable (used for testing)

What steps will reproduce the problem?
1. Install tesseract 3.0.2
2. Follow instructions to compile leptonica lib and libocrivist tessintf lib
3. Got these errors in the make step for libocrivist:
 svutil.cpp -o svutil.o
svutil.cpp: In static member function ‘static void SVSync::StartProcess(const 
char*, const char*)’:
svutil.cpp:91:18: error: ‘fork’ was not declared in this scope
   int pid = fork();
                  ^
svutil.cpp:121:28: error: ‘execvp’ was not declared in this scope
     execvp(executable, argv);
                            ^
svutil.cpp: In member function ‘void SVNetwork::Close()’:
svutil.cpp:264:16: error: ‘close’ was not declared in this scope
   close(stream_);
                ^
svutil.cpp: In constructor ‘SVNetwork::SVNetwork(const char*, int)’:
svutil.cpp:419:14: error: ‘sleep’ was not declared in this scope
       sleep(1);
              ^



What is the expected output? What do you see instead?
See above.

What version of the product are you using? On what operating system?
Followed instructions on wiki page: libocrivist-3.00r4.tar.gz

Please provide any additional information below.
Perhaps it's an option to switch from a custom build with C API to generating 
object-oriented .pas files with SWIG from C++ headers.
Please see http://wiki.lazarus.freepascal.org/SWIG for details.

```

Original issue reported on code.google.com by `reiniero...@gmail.com` on 19 Jul 2013 at 10:05

**Comment by GoogleCodeExporter** [comment]
```
Oh, there's also capi.cpp and capi.h in tesseract 3.02.02... which may be more 
easy to adapt?
```

Original comment by `reiniero...@gmail.com` on 19 Jul 2013 at 11:04

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Libocrivist should only be compiled with tesseract 3.00.

Since SVN release #164 the SVN version of Ocrivist no longer uses libocrivist 
but accesses libtesseract 3.02  directly.
```

Original comment by `malcol...@gmail.com` on 1 Nov 2013 at 3:56

**Comment by GoogleCodeExporter** [comment]
Original comment by `malcol...@gmail.com` on 5 Jun 2015 at 11:45
- Changed state: **Fixed**
